# Generated by Django 4.0.4 on 2022-06-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_job_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interviwer',
            new_name='interviewer',
        ),
    ]
